### ISSUE TITLE
update minimalist and acorn

### ISSUE THREAD

**Issue by LennertSchepers** [EMODnet/OSL2-ByteBear#4]
Dear @bytesnz 
We get a notification that we should update 2 libs in the ByteBear repository of the OpenSeaLab last year:

- Upgrade acorn to version 5.7.4 or later. 

- Upgrade minimist to version 0.2.1 or later.

Dependabot cannot create a pull request as one or more other dependencies require a version that is incompatible with this update

Could you fix this?
Thanks

**Comment by bart-v** [comment]
Acorn upgraded to 8.8.2 https://github.com/EMODnet/OSL2-ByteBear/pull/40
Minimist is now at 1.2.6
